<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images/Wordclock.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Images/*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
  </ItemGroup>

</Project>