<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Images/Wordclock.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties/" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="FodyWeavers.xml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images/WordClock.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images/Color.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images/Close.png" />
    <Resource Include="Images/maximize.png" />
    <Resource Include="Images/minimize.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images/OnTopmostOff.ico" />
    <Resource Include="Images/OnTopmostOn.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
  </ItemGroup>
</Project>